name: Test Child
on: 
  pull_request:

permissions: {}

jobs:
  Job1:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          if [ "${{ secrets.TEST_SECRET }}" == "123" ]; then
            echo "Match"
          else
            echo "Not matched"
          fi
